-- MySQL Script generated by MySQL Workbench
-- Mon May 17 21:46:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema userInfoDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userInfoDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userInfoDb` DEFAULT CHARACTER SET utf8 ;
USE `userInfoDb` ;

-- -----------------------------------------------------
-- Table `userInfoDb`.`userInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userInfoDb`.`userInfo` (
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `addr` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `budget` VARCHAR(200) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
